<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\KaanAI.Application.Abstraction\KaanAI.Application.Abstraction.csproj" />
      <ProjectReference Include="..\KaanAI.Persistence\KaanAI.Persistence.csproj" />
    </ItemGroup>

</Project>
