<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="src/OpenWeatherMap/Contracts/" />
    <Folder Include="src/SemanticKernel/Contracts/" />
    <Folder Include="src\Chat\Contracts\" />
  </ItemGroup>

</Project>
